services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-s", "-u", "elastic:${ELASTIC_PASSWORD}", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 30
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks: [esnet]

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=kibanapass
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks: [esnet]

  api:
    build: ./api
    environment:
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - INDEX_NAME=products
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./api/app:/app/app
    ports:
      - "${API_PORT}:8000"
    networks: [esnet]

volumes:
  esdata:

networks:
  esnet:
